sudo: required
dist: trusty
language: node_js

services:
  - docker

node_js:
- 8.11.3

after_success:
  - sh .travis/deploy_dockerhub.sh
  - #sh test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
